version: '3'
services:
    pma:
      image: adminer
      ports:
        - "8080:8080"
      depends_on:
        - db
      networks:
        - legacy
    maildev:
      image: djfarrelly/maildev
      ports:
       - "1080:80"
      networks:
        legacy:
          aliases:
           - maildev
    # bind dev services on main app
    web:
      depends_on:
        - maildev